# Generated by Django 6.0.3 on 2026-04-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_invite", models.BooleanField(default=False)),
                ("agree_delete", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="Event.event",
                    ),
                ),
            ],
        ),
    ]
