[tool.poetry]
package-mode = false

[project]
name = "promise-app"
version = "0.1.0"
description = ""
authors = [
    {name = "kihoon",email = "nike6736@naver.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.0.3,<7.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "drf-spectacular (>=0.29.0,<0.30.0)",
    "black (>=26.3.1,<27.0.0)"
]



[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^26.3.1"
ruff = "^0.15.8"
mypy = "^1.20.0"
django-stubs = "^6.0.2"


# mypy 도구에 대한 전반적인 설정을 시작하는 섹션
coverage = "^7.13.5"
djangorestframework-stubs = "^3.16.9"

[tool.mypy]
# mypy가 사용할 외부 플러그인 목록에 장고 플러그인을 지정하여 활성화함
plugins = [
    "mypy_django_plugin.main", # Django 전용 분석 플러그인
    "mypy_drf_plugin.main"     # Django REST Framework 전용 분석 플러그인
]

# mypy 장고 플러그인을 위한 세부 설정을 시작하는 섹션
[tool.django-stubs]
# 장고 프로젝트의 전반적인 환경 설정 파일이 어디에 있는지 경로를 알려줌
django_settings_module = "config.settings"

[tool.black]
# Black이 코드를 포맷팅할 때 파이썬 3.13 버전을 기준으로 동작하도록 영구적으로 설정
target-version = ['py313']