"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-q*a%gpy*v964a@o-ovx1zzlt8wh)!b_q1_t#&c#litaqs!!isi"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition

DJANGO_APPS = [  # 장고 프레임워크가 기본으로 제공하는 앱 목록입니다.
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS: list[str] = [
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
]  # 외부에서 설치한 라이브러리 앱들입니다.

CUSTOM_APPS = [
    "apps.User",
    "apps.Event",
    "apps.EventMember",
    "apps.TimeSlot",
    "apps.PlaceCandidate",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + CUSTOM_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # 이 DIRS 리스트 안에 BASE_DIR / 'templates'를 추가해야 최상위 폴더의 templates를 인식함
        "DIRS": [BASE_DIR / "templates"],
        # 각 앱 폴더 내부의 templates 폴더도 자동으로 검색하도록 설정
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # 디버그 정보를 템플릿에서 쓸 수 있게 합니다.
                "django.template.context_processors.debug",
                # 뷰의 request 객체를 템플릿에서 쓸 수 있게 합니다.
                "django.template.context_processors.request",
                # 로그인한 유저 정보를 템플릿에서 쓸 수 있게 합니다.
                "django.contrib.auth.context_processors.auth",
                # 시스템 메시지 기능을 템플릿에서 쓸 수 있게 합니다.
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get(
            "POSTGRES_DB", "promise_db"
        ),  # 운영체제 환경변수에서 값을 꺼내옵니다.
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "your_secret_password"),
        "HOST": os.environ.get(
            "POSTGRES_HOST", "promise_db"
        ),  # docker-compose에서 설정한 HOST를 바라봅니다.
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# 장고의 기본 인증 모델 대신 만든 User 앱의 User 모델을 사용하도록 지정
AUTH_USER_MODEL = "User.User"

# 장고 레스트 프레임워크의 전역적인 작동 방식을 세밀하게 제어하는 설정 딕셔너리
REST_FRAMEWORK = {
    # 기존에 작성하신 스펙타큘러 자동화 스키마 설정
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # API 요청이 들어올 때 누구인지 확인하는 기본 인증 방식들을 지정
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # JWT 토큰을 해독하여 올바른 사용자인지 검증하는 라이브러리 클래스를 등록
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# 스웨거 웹 페이지 화면 상단에 노출될 프로젝트의 간판 정보들을 설정하는 딕셔너리
SPECTACULAR_SETTINGS = {
    # 완성된 스웨거 문서의 가장 눈에 띄는 곳에 표시될 공식 서비스 이름을 지정
    "TITLE": "Promise App API",
    "DESCRIPTION": "약속 잡기 어플리케이션을 위한 백엔드 API 명세서입니다.",
    # 현재 API의 버전을 숫자로 명시하여 나중에 기능이 크게 변경되었을 때 헷갈리지 않도록 돕기
    "VERSION": "1.0.0",
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # 정적 파일들이 모일 폴더 위치를 지정합니다.

# Media files (사용자가 업로드하는 파일들)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"  # 사용자가 업로드한 파일이 저장될 위치를 지정합니다.
